; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Librepods"
#ifndef MyAppVersion
#define MyAppVersion "1.0.0-b"
#endif
#define MyAppExeName "librepods-windows.exe"
#define DriverInfName "BthEchoSampleCli.inf"
#define DriverCatName "kmdfsamples.cat"
#define DriverCerName "l2cap-bridge.cer"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{86D0F8A0-C8A9-4782-9346-2CAA1A4C2AA8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\Librepods-windowsbridge
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
; Admin is required: installing the AAP L2CAP kernel driver (pnputil) and
; trusting its signing cert (LocalMachine cert stores) both need elevation.
PrivilegesRequired=admin
OutputDir=Output
OutputBaseFilename=librepods-windowsbridge-{#MyAppVersion}-setup
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "build\dist\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

; AAP L2CAP driver package (see driver\README.md for how to populate this
; folder before compiling the installer). skipifsourcedoesntexist lets the
; installer still build if it's empty during development; in that case the
; [Run] steps below are skipped too, since they check the files exist.
Source: "driver\{#DriverInfName}"; DestDir: "{app}\driver"; Flags: skipifsourcedoesntexist
Source: "driver\BthEchoSampleCli.sys"; DestDir: "{app}\driver"; Flags: skipifsourcedoesntexist
Source: "driver\{#DriverCatName}"; DestDir: "{app}\driver"; Flags: skipifsourcedoesntexist
Source: "driver\{#DriverCerName}"; DestDir: "{app}\driver"; Flags: skipifsourcedoesntexist
; Uninstall helper: removes the driver package and, importantly, the signing
; cert from LocalMachine\Root so no third-party code-signing root is left
; trusted on the machine after uninstall.
Source: "uninstall-driver.ps1"; DestDir: "{app}"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Trust the driver's signing cert, then install the driver package. Requires
; the machine to already be in test-signing mode (bcdedit /set testsigning on,
; reboot, Secure Boot off) - the installer does not flip that for you.
Filename: "{sys}\certutil.exe"; Parameters: "-addstore Root ""{app}\driver\{#DriverCerName}"""; \
    StatusMsg: "Trusting the AAP L2CAP driver certificate..."; Flags: runhidden waituntilterminated; \
    Check: DriverFilesPresent
Filename: "{sys}\certutil.exe"; Parameters: "-addstore TrustedPublisher ""{app}\driver\{#DriverCerName}"""; \
    StatusMsg: "Trusting the AAP L2CAP driver certificate..."; Flags: runhidden waituntilterminated; \
    Check: DriverFilesPresent
Filename: "{sys}\pnputil.exe"; Parameters: "/add-driver ""{app}\driver\{#DriverInfName}"" /install"; \
    StatusMsg: "Installing the AAP L2CAP driver..."; Flags: runhidden waituntilterminated; \
    Check: DriverFilesPresent
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Remove the driver and the trusted signing cert on uninstall. runascurrentuser
; is fine here - the uninstaller already runs elevated (PrivilegesRequired=admin).
Filename: "powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -File ""{app}\uninstall-driver.ps1"""; \
    StatusMsg: "Removing the AAP L2CAP driver..."; Flags: runhidden waituntilterminated; \
    RunOnceId: "RemoveAapDriver"

[Code]
function DriverFilesPresent: Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\driver\{#DriverInfName}'))
    and FileExists(ExpandConstant('{app}\driver\{#DriverCatName}'))
    and FileExists(ExpandConstant('{app}\driver\{#DriverCerName}'));
end;
